# This is a basic workflow to help you get started with Actions

name: Update Submodule

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  repository_dispatch:
    types:
      - update

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Show message
        run: echo "submodule updated"
